# Generated by Django 3.2.8 on 2022-05-22 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discountcode',
            old_name='expire_data',
            new_name='expire_date',
        ),
    ]
