# Generated by Django 3.2.8 on 2022-05-25 18:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tours', '0002_rename_expire_data_discountcode_expire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='bookers',
            field=models.ManyToManyField(blank=True, related_name='tours', to=settings.AUTH_USER_MODEL),
        ),
    ]
