# Generated by Django 3.2.8 on 2022-05-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_auto_20220527_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
