# Generated by Django 3.2.8 on 2023-05-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_auto_20230522_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='tour_type',
            field=models.CharField(choices=[('0', 'فرهنگی'), ('1', 'ماجراجویی'), ('2', 'تفریحی'), ('3', 'حیات وحش'), ('4', 'آشپزی'), ('5', 'معنوی'), ('6', 'عکاسی'), ('7', 'تاریخی'), ('8', 'طبیعت گردی'), ('9', 'کویری'), ('10', 'قطاری'), ('11', 'یک روزه'), ('12', 'سایر')], default='12', max_length=20),
        ),
    ]
