# Generated by Django 3.2.8 on 2023-05-22 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_alter_tour_tour_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='start_point',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='transportation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
