# Generated by Django 3.2.8 on 2023-05-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_auto_20230523_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='x_location',
            field=models.DecimalField(decimal_places=15, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='y_location',
            field=models.DecimalField(decimal_places=15, max_digits=20, null=True),
        ),
    ]
