# Generated by Django 3.2.8 on 2023-04-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='get_notified',
            field=models.BooleanField(default=True),
        ),
    ]
