# Generated by Django 3.2.8 on 2022-03-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='username',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
