# Generated by Django 3.2.8 on 2022-03-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_verification_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('uid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
