# Generated by Django 3.2.8 on 2023-04-30 12:29

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_favorite_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_tour_types',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('0', 'فرهنگی'), ('1', 'ماجراجویی'), ('2', 'تفریحی'), ('3', 'حیات وحش'), ('4', 'آشپزی'), ('5', 'معنوی'), ('6', 'عکاسی'), ('7', 'تاریخی'), ('8', 'طبیعت گردی'), ('9', 'سفرهای آموزشی'), ('10', 'سایر')], max_length=22, null=True),
        ),
    ]
