# Generated by Django 3.2.8 on 2023-05-01 20:10

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_favorite_tour_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite_categories',
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_event_types',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('0', 'همایش'), ('1', 'نمایشگاه'), ('2', 'نمایش'), ('3', 'کنسرت یا اجرا'), ('4', 'جشنواره'), ('5', 'مسابقه'), ('6', 'کنفرانس'), ('7', 'سمینار'), ('8', 'مجمع'), ('9', 'جشن'), ('10', 'مراسم'), ('11', 'سایر')], max_length=25, null=True),
        ),
    ]
