# Generated by Django 3.2.8 on 2022-04-21 14:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_about_me'),
    ]

    operations = [

    ]
