# Generated by Django 3.2.8 on 2022-04-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_about_me'),
    ]

    operations = [

    ]
