# Generated by Django 3.2.8 on 2023-05-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20230501_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagedpayments',
            name='amount',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='wallet_credit',
            field=models.BigIntegerField(null=True),
        ),
    ]
