# Generated by Django 3.2.8 on 2022-04-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220421_1918'),
    ]

    operations = [

    ]
