# Generated by Django 3.2.8 on 2023-05-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20230513_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wallet_credit',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
