# Generated by Django 3.2.8 on 2023-05-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_wallet_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dimonds',
            field=models.IntegerField(default=0),
        ),
    ]
