# Generated by Django 3.2.8 on 2022-05-08 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_stagedpayments'),
        ('accounts', '0009_specialuser'),
    ]

    operations = [
    ]
