# Generated by Django 3.2.8 on 2022-05-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20220509_0102'),
    ]

    operations = [
        
    ]
