# Generated by Django 3.2.8 on 2022-05-08 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20220509_0112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='specialuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='specialuser',
            name='user_ptr',
        ),
    ]
