# Generated by Django 3.2.8 on 2022-05-10 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_following'),
        ('accounts', '0013_auto_20220509_0338'),
    ]

    operations = [
    ]
