# Generated by Django 3.2.8 on 2022-05-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_merge_0008_user_following_0013_auto_20220509_0338'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='user',
        #     name='first_name',
        #     field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        # ),
        # migrations.AddField(
        #     model_name='user',
        #     name='follower_number',
        #     field=models.IntegerField(default=0),
        # ),
        # migrations.AddField(
        #     model_name='user',
        #     name='following_number',
        #     field=models.IntegerField(default=0),
        # ),
        # migrations.AddField(
        #     model_name='user',
        #     name='full_name',
        #     field=models.CharField(blank=True, max_length=255, null=True),
        # ),
        # migrations.AddField(
        #     model_name='user',
        #     name='last_name',
        #     field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        # ),
    ]
