# Generated by Django 3.2.8 on 2022-05-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_merge_0008_user_following_0013_auto_20220509_0338'),
    ]

    operations = [

    ]
