# Generated by Django 3.2.8 on 2022-05-10 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20220510_1536'),
        ('accounts', '0015_auto_20220510_2119'),
    ]

    operations = [
    ]
