# Generated by Django 3.2.8 on 2023-04-26 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventsuggestion',
            old_name='reciver',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='placesuggestion',
            old_name='reciver',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='toursuggestion',
            old_name='reciver',
            new_name='receiver',
        ),
    ]
