# Generated by Django 3.2.8 on 2023-05-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestion', '0002_auto_20230426_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsuggestion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='placesuggestion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='toursuggestion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
