# Generated by Django 3.2.8 on 2022-04-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20220423_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='x_location',
            field=models.DecimalField(decimal_places=3, default=50, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='y_location',
            field=models.DecimalField(decimal_places=3, default=89, max_digits=6),
            preserve_default=False,
        ),
    ]
