# Generated by Django 3.2.8 on 2022-04-25 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20220425_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='places.place'),
        ),
        migrations.AlterField(
            model_name='optional',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optional_costs', to='places.place'),
        ),
        migrations.AlterField(
            model_name='room',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='places.place'),
        ),
    ]
