# Generated by Django 3.2.8 on 2022-06-16 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_hours'),
        ('places', '0006_place_date_created'),
    ]

    operations = [
    ]
