# Generated by Django 3.2.8 on 2022-06-15 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='start_time',
        ),
    ]
