# Generated by Django 3.2.8 on 2022-06-15 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_auto_20220615_2003'),
        ('places', '0007_merge_0006_hours_0006_place_date_created'),
    ]

    operations = [
    ]
