# Generated by Django 3.2.8 on 2023-04-21 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('0', 'همایش'), ('1', 'نمایشگاه'), ('2', 'نمایش'), ('3', 'کنسرت یا اجرا'), ('4', 'جشنواره'), ('5', 'مسابقه'), ('6', 'کنفرانس'), ('7', 'سمینار'), ('8', 'مجمع'), ('9', 'جشن'), ('10', 'مراسم'), ('11', 'سایر')], default='11', max_length=20)),
                ('event_category', models.CharField(choices=[('0', 'هنری'), ('1', 'علمی'), ('2', 'فرهنگی'), ('3', 'ورزشی'), ('4', 'سیاسی'), ('5', 'اجتماعی'), ('6', 'مذهبی'), ('7', 'تجاری'), ('8', 'سایر')], default='8', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('organizer', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('x_location', models.DecimalField(decimal_places=15, max_digits=20)),
                ('y_location', models.DecimalField(decimal_places=15, max_digits=20)),
                ('province', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('address', models.CharField(max_length=255)),
                ('is_free', models.BooleanField(blank=True, default=False)),
                ('website', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/events')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='events.event')),
            ],
        ),
    ]
