# Generated by Django 3.2.8 on 2023-04-14 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('0', 'سایر'), ('1', 'جشنواره'), ('2', 'کنسرت موسیقی'), ('3', 'مسابقه'), ('4', 'مهمانی و دورهمی')], default='0', max_length=20)),
                ('event_category', models.CharField(choices=[('0', 'سایر'), ('1', 'خانوادگی'), ('2', 'هنری'), ('3', 'بیزنسی'), ('4', 'مذهبی')], default='0', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('organizer', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('x_location', models.DecimalField(decimal_places=10, max_digits=15)),
                ('y_location', models.DecimalField(decimal_places=10, max_digits=15)),
                ('province', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/events')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='events.event')),
            ],
        ),
    ]
