# Generated by Django 3.2.8 on 2023-05-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
