# Generated by Django 3.2.8 on 2023-05-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_active',
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('AC', 'Accepted'), ('DN', 'Denied'), ('PN', 'Pending')], default='PN', max_length=2),
        ),
    ]
