# Generated by Django 3.2.8 on 2023-04-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20230415_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(default='teh', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='is_free',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
