# Generated by Django 3.2.8 on 2023-04-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20230415_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_category',
            field=models.CharField(choices=[('0', 'هنری'), ('1', 'علمی'), ('2', 'فرهنگی'), ('3', 'ورزشی'), ('4', 'سیاسی'), ('5', 'اجتماعی'), ('6', 'مذهبی'), ('7', 'تجاری'), ('8', 'سایر')], default='8', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('0', 'همایش'), ('1', 'نمایشگاه'), ('2', 'نمایش'), ('3', 'کنسرت یا اجرا'), ('4', 'جشنواره'), ('5', 'مسابقه'), ('6', 'کنفرانس'), ('7', 'سمینار'), ('8', 'مجمع'), ('9', 'جشن'), ('10', 'مراسم'), ('11', 'سایر')], default='11', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='x_location',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='y_location',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
    ]
