# Generated by Django 3.2.8 on 2023-04-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20230416_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='website',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
