# Generated by Django 3.2.8 on 2022-05-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0002_auto_20220504_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='rate_no',
            field=models.IntegerField(default=5),
        ),
    ]
