# Generated by Django 3.2.8 on 2022-05-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0003_experience_rate_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='experience',
            name='rate_no',
            field=models.IntegerField(default=0),
        ),
    ]
