# Generated by Django 3.2.8 on 2022-05-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0004_auto_20220504_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='image',
            field=models.ImageField(upload_to='images/experiences'),
        ),
    ]
