# Generated by Django 3.2.8 on 2022-05-04 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('experience', '0005_alter_experience_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='accounts.user'),
            preserve_default=False,
        ),
    ]
