# Generated by Django 3.2.8 on 2022-05-04 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0006_auto_20220504_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='rate_no',
        ),
    ]
