# Generated by Django 3.2.8 on 2022-05-04 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0007_remove_experience_rate_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='views',
        ),
        migrations.AlterField(
            model_name='experience',
            name='rate',
            field=models.IntegerField(default=5),
        ),
    ]
