# Generated by Django 3.2.8 on 2022-05-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0008_auto_20220505_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
