# Generated by Django 3.2.8 on 2022-05-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0011_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/experiences'),
        ),
    ]
