# Generated by Django 3.2.8 on 2022-05-07 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0011_alter_experience_image'),
        ('experience', '0011_comment'),
    ]

    operations = [
    ]
