# Generated by Django 3.2.8 on 2022-05-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0015_alter_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='date',
            field=models.DateField(default=None, null=True),
        ),
    ]
