# Generated by Django 3.2.8 on 2022-05-30 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0016_like_date'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='comment',
        #     name='parent',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='experience.comment'),
        # ),
    ]
