# Generated by Django 3.2.8 on 2022-07-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_chat_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='sender_type',
            field=models.CharField(choices=[('SERVER', 'Server'), ('CLIENT', 'Clinet')], max_length=6, null=True),
        ),
    ]
