# Generated by Django 3.2.8 on 2023-04-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_messageroom_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageroom',
            name='type',
            field=models.CharField(choices=[('PV', 'Pv'), ('GROUP', 'Group')], default='PV', max_length=6, null=True),
        ),
    ]
