# Generated by Django 3.2.8 on 2023-04-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_messageroom_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageroom',
            name='type',
            field=models.CharField(blank=True, choices=[('PV', 'Pv'), ('GROUP', 'Group')], default='PV', max_length=6, null=True),
        ),
    ]
