# Generated by Django 3.2.8 on 2023-05-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_title', models.CharField(max_length=256)),
                ('email_body', models.TextField()),
                ('sender', models.EmailField(max_length=254)),
                ('receiver', models.EmailField(max_length=254)),
                ('state', models.CharField(choices=[('0', 'wait'), ('1', 'sent'), ('2', 'idle')], default='0', max_length=2)),
            ],
        ),
    ]
