name: Django CD

on: [push]

jobs:
  deploy:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name : test commands
      run: pwd |
        git status |
