name: Django CD

on: [push]

jobs:
  deploy:
    permissions: write-all
    runs-on: self-hosted
    steps:
    - name : test commands
      run: cd /home/ubuntu/Irangard_Backend/ && git pull && irback
