name: Push to Production

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ master, develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v2
    
      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: production 
          FOLDER: .
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          MESSAGE: "Build: ({sha}) {msg}" 
