name: Django CD

on: [push]

jobs:
  deploy:
    permissions: write-all
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:latest


    steps:
    - uses: actions/checkout@v3
    - name : test commands
      run: pwd |
        git status |
        ls -la |
        cd Irangard/Irangard/ |
        touch .env
