name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name : env file
      run : |
        touch Irangard/Irangard/.env && printf "export DEBUG=True\nexport SECRET_KEY='django-insecure-g&@l9t5+dmgmtyi7p=@quy8h&+%@pgsb1v&0njdsfd@q6=w1gs'\nexport DB_PASSWORD='1234'\nexport WEBSITE_URL='http://127.0.0.1:8000'\nexport EMAIL_ID='irangard.se@gmail.com'\nexport EMAIL_PW='wfxwebonohrrbatv'\nexport DB_HOST='localhost'\nexport DB_NAME='dbirangard'\nexport DB_USER='postgres'" >> Irangard/Irangard/.env 
    - name : see .env
      run : cat Irangard/Irangard/.env
    - name: Run Tests
      run: |
        pwd && ls && python Irangard/manage.py test
